services:
  collector:
    image: yuyangruan/ths-redroid:1.2.50-headless
    privileged: true
    restart: unless-stopped
    environment:
      THS_MODE: collector
      THS_INSTANCE_ID: collector-example
    volumes:
      - collector-data:/data
    ports:
      - "127.0.0.1:5570:5555"
      - "127.0.0.1:49620:18900"
    dns:
      - 10.168.1.3
      - 223.5.5.5
    command:
      - ro.product.cpu.abilist=x86_64,arm64-v8a,x86,armeabi-v7a,armeabi
      - ro.product.cpu.abilist64=x86_64,arm64-v8a
      - ro.product.cpu.abilist32=x86,armeabi-v7a
      - ro.dalvik.vm.isa.arm=x86
      - ro.dalvik.vm.isa.arm64=x86_64
      - ro.enable.native.bridge.exec=1
      - ro.vendor.enable.native.bridge.exec=1
      - ro.vendor.enable.native.bridge.exec64=1
      - ro.dalvik.vm.native.bridge=libriruloader.so
      - androidboot.redroid_gpu_mode=guest
      - androidboot.use_memfd=1
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G

volumes:
  collector-data:
