"""ORM 模型 — 与 schema/*.sql 一一对应

所有模型继承 base.Base,通过 import 触发注册到 Base.registry。
"""
from src.infrastructure.persistence.models.base import Base
from src.infrastructure.persistence.models.collection import (
    CollectionRun,
    CollectionState,
    EtfDailyShare,
    InstrumentDisclosure,
    InstrumentObservation,
    InstrumentProfile,
    MacroIndicator,
    MarketCache,
    MarketFlow,
    MarketSnapshot,
    News,
    Sentiment,
)
from src.infrastructure.persistence.models.trading import (
    Decision,
    FundLimit,
    IndexFund,
    IndustryIndex,
    IndustryMapping,
    PendingDecision,
    Position,
    Trade,
)
from src.infrastructure.persistence.models.reflection import (
    Lesson,
    Review,
)
from src.infrastructure.persistence.models.llm import LLMCallLog
from src.infrastructure.persistence.models.knowledge import (
    KnowledgeAssignmentCandidateOrder,
    KnowledgeCardRelation,
    KnowledgeCognitiveCard,
    KnowledgeCompilationRun,
    KnowledgeCommunityAssignment,
    KnowledgeCommunityInsight,
    KnowledgeEvidenceChunk,
    KnowledgeEvidence,
    KnowledgeGraphCommunity,
    KnowledgeGraphCommunityRelation,
    KnowledgeGraphFinding,
    KnowledgeGraphUnassignedSignal,
    KnowledgeNormalizationRule,
    KnowledgeRetrievalEvalMetric,
    KnowledgeRetrievalEvalRun,
    KnowledgeRetrievalLabel,
    KnowledgeRetrievalTraceSnapshot,
    KnowledgeReviewItem,
    KnowledgeVersion,
)
from src.infrastructure.persistence.models.agent_research import (
    AgentCurrentResearchReport,
    AgentInvestmentView,
    AgentInvestmentViewRevision,
    AgentResearchClaim,
    AgentResearchForecast,
    AgentResearchObservationRequirement,
    AgentResearchOutcomeEvaluation,
    AgentResearchOutcomeObservation,
    AgentResearchQualityEvaluation,
    AgentResearchReportRevision,
    AgentResearchRun,
    AgentRoleMemoryCase,
    AgentRoleMemoryItem,
    AgentRuntimeRun,
    AgentToolInvocation,
)

__all__ = [
    "Base",
    # collection
    "News",
    "MarketFlow",
    "MarketCache",
    "MarketSnapshot",
    "EtfDailyShare",
    "InstrumentProfile",
    "InstrumentDisclosure",
    "InstrumentObservation",
    "CollectionRun",
    "Sentiment",
    "MacroIndicator",
    "CollectionState",
    # trading
    "PendingDecision",
    "Decision",
    "Trade",
    "Position",
    "IndustryMapping",
    "IndustryIndex",
    "IndexFund",
    "FundLimit",
    # reflection
    "Review",
    "Lesson",
    # llm
    "LLMCallLog",
    # knowledge
    "KnowledgeAssignmentCandidateOrder",
    "KnowledgeCardRelation",
    "KnowledgeCognitiveCard",
    "KnowledgeCommunityAssignment",
    "KnowledgeCommunityInsight",
    "KnowledgeNormalizationRule",
    "KnowledgeEvidence",
    "KnowledgeVersion",
    "KnowledgeReviewItem",
    "KnowledgeCompilationRun",
    "KnowledgeGraphCommunity",
    "KnowledgeGraphCommunityRelation",
    "KnowledgeGraphFinding",
    "KnowledgeGraphUnassignedSignal",
    "KnowledgeEvidenceChunk",
    "KnowledgeRetrievalTraceSnapshot",
    "KnowledgeRetrievalLabel",
    "KnowledgeRetrievalEvalRun",
    "KnowledgeRetrievalEvalMetric",
    # agent research
    "AgentResearchRun",
    "AgentCurrentResearchReport",
    "AgentResearchReportRevision",
    "AgentInvestmentView",
    "AgentInvestmentViewRevision",
    "AgentResearchClaim",
    "AgentResearchForecast",
    "AgentResearchObservationRequirement",
    "AgentResearchOutcomeObservation",
    "AgentResearchOutcomeEvaluation",
    "AgentResearchQualityEvaluation",
    "AgentRoleMemoryItem",
    "AgentRoleMemoryCase",
    "AgentRuntimeRun",
    "AgentToolInvocation",
]
