"""Persistent cache for LLM proxy responses."""

from __future__ import annotations

import json
import logging
import os
import tempfile
import time
from pathlib import Path
from typing import Any

from src.infrastructure.llm_proxy.types import LLMProxyResponse

logger = logging.getLogger(__name__)


class LLMPersistentFileCache:
    """Small JSON-file cache keyed by a stable request hash.

    The cache intentionally stores only the normalized response, not the prompt.
    The filename is the request hash generated by the gateway.
    """

    def __init__(self, cache_dir: str | Path, *, enabled: bool = True):
        self.cache_dir = Path(cache_dir)
        self.enabled = enabled
        if self.enabled:
            self.cache_dir.mkdir(parents=True, exist_ok=True)

    def get(self, key: str) -> LLMProxyResponse | None:
        if not self.enabled:
            return None
        path = self._path_for(key)
        if not path.exists():
            return None
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
            response = payload.get("response")
            if not isinstance(response, dict):
                return None
            if not response.get("text") and response.get("structured_output") is None:
                return None
            return LLMProxyResponse(
                text=str(response.get("text") or ""),
                structured_output=response.get("structured_output"),
                usage=dict(response.get("usage") or {}),
                session_id=response.get("session_id"),
                duration_ms=int(response.get("duration_ms") or 0),
                raw_payload=dict(response.get("raw_payload") or {}),
                cache_hit=True,
                proxy=dict(response.get("proxy") or {}),
            )
        except Exception as exc:
            logger.warning("[llm_proxy_cache] read failed key=%s path=%s error=%s", key, path, exc)
            return None

    def set(self, key: str, response: LLMProxyResponse) -> None:
        if not self.enabled:
            return
        path = self._path_for(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "version": 1,
            "created_at": time.time(),
            "response": {
                "text": response.text,
                "structured_output": response.structured_output,
                "usage": response.usage,
                "session_id": response.session_id,
                "duration_ms": response.duration_ms,
                "raw_payload": response.raw_payload,
                "proxy": response.proxy,
            },
        }
        try:
            data = json.dumps(payload, ensure_ascii=False, sort_keys=True, default=str)
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                dir=str(path.parent),
                delete=False,
                prefix=f".{path.name}.",
                suffix=".tmp",
            ) as handle:
                handle.write(data)
                tmp_path = Path(handle.name)
            os.replace(tmp_path, path)
        except Exception as exc:
            logger.warning("[llm_proxy_cache] write failed key=%s path=%s error=%s", key, path, exc)

    def stats(self) -> dict[str, Any]:
        return {
            "enabled": self.enabled,
            "dir": str(self.cache_dir),
        }

    def _path_for(self, key: str) -> Path:
        safe_key = "".join(ch for ch in key if ch.isalnum())[:128]
        if len(safe_key) < 16:
            raise ValueError("cache key is too short")
        return self.cache_dir / safe_key[:2] / f"{safe_key}.json"
