[program:frpc_langfuse]
command=/home/yuyangruan/frp_0.52.3_linux_amd64/frpc -c /home/yuyangruan/frp_0.52.3_linux_amd64/frpc_langfuse.toml
directory=/home/yuyangruan/frp_0.52.3_linux_amd64
autostart=true
autorestart=true
stderr_logfile=/var/log/frpc_langfuse.err.log
stdout_logfile=/var/log/frpc_langfuse.out.log
user=yuyangruan
